import os
DEBUG = True

SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY='[YOUR_SECRET_KEY]'


# DATABASE = 'postgresql'
SQLALCHEMY_DATABASE_URI = "postgresql://[USERNAME]:[PASSWORD]@[HOST]:[PORT]/[DATABASENAME]";